# IMAGE SEGMENTATION USING UNSUPERVISED GAUSSIAN MIXTURE MODEL (GMM) CLUSTERING

Rock Image

## 1. Importing Python Libraries

In [1]:
import numpy as np
import cv2

from sklearn.mixture import GaussianMixture as GMM

print("Python Libraries Import Completed")

Python Libraries Import Completed


## 2. Importing the Image File

In [2]:
# Importing Image
image1 = cv2.imread("/content/drive/MyDrive/~~~VP_Data_Science/DS_Real_Time_Projects/Image_Segmentation_Using_UnSupervised_Gaussian_Mixture_Model_GMM_Clustering/data/rock.jpg")

print("Image Import Completed")

Image Import Completed


## 3. Image Exploration

In [3]:
# Displaying the Imported Image

image1

array([[[ 66,  66,  66],
        [ 59,  59,  59],
        [ 88,  88,  88],
        ...,
        [100, 100, 100],
        [ 35,  35,  35],
        [ 34,  34,  34]],

       [[ 51,  51,  51],
        [ 45,  45,  45],
        [127, 127, 127],
        ...,
        [ 98,  98,  98],
        [117, 117, 117],
        [ 52,  52,  52]],

       [[ 94,  94,  94],
        [ 69,  69,  69],
        [ 75,  75,  75],
        ...,
        [ 95,  95,  95],
        [127, 127, 127],
        [  6,   6,   6]],

       ...,

       [[130, 130, 130],
        [141, 141, 141],
        [106, 106, 106],
        ...,
        [114, 114, 114],
        [204, 204, 204],
        [190, 190, 190]],

       [[108, 108, 108],
        [122, 122, 122],
        [103, 103, 103],
        ...,
        [104, 104, 104],
        [187, 187, 187],
        [ 85,  85,  85]],

       [[ 91,  91,  91],
        [133, 133, 133],
        [133, 133, 133],
        ...,
        [134, 134, 134],
        [ 79,  79,  79],
        [ 90,  90,  90]]

In [4]:
# Verifying the Type of the Image

type(image1)

numpy.ndarray

In [5]:
# Verifying the Shape of the Image

image1.shape

(861, 1024, 3)

## 4. Image Pre-Processing (Reshaping)

In [6]:
# Reshaping the Image

#image1_reshape = image1.reshape(861, 1024, 3)
image1_reshape = image1.reshape((-1, 3))

print("Execution Completed")

Execution Completed


In [7]:
# Displaying the Reshaped Image
image1_reshape

array([[ 66,  66,  66],
       [ 59,  59,  59],
       [ 88,  88,  88],
       ...,
       [134, 134, 134],
       [ 79,  79,  79],
       [ 90,  90,  90]], dtype=uint8)

In [8]:
# Verifying the Type of the Reshaped Image

type(image1_reshape)

numpy.ndarray

In [9]:
# Verifying the Shape of the Reshaped Image

image1_reshape.shape

(881664, 3)

## 5. UnSupervised Clustering - Gaussian Mixture Model Fitting

### 5.1 GMM Clustering Default Parameters Configuration

In [33]:
# GMM Parameters Initial Configuration

n_components = 4
covariance_type = "full"
tol = 0.001
reg_covar = 0.000001
max_iter = 100
n_init = 1
init_params = "kmeans"
weights_init = None
means_init = None
precisions_init = None
random_state = None
warm_start = False
verbose = 0
verbose_interval = 10

print("Execution Completed")

Execution Completed


### 5.2 GMM Clustering Model Definition and Initiation

In [34]:
# Defining and Initiating an Instance of GMM Clustering Model

gmm_model = GMM(n_components=n_components, covariance_type=covariance_type, tol=tol, reg_covar=reg_covar, 
                 max_iter=max_iter, n_init=n_init, init_params=init_params, weights_init=weights_init, 
                 means_init=means_init, precisions_init=precisions_init, random_state=random_state, 
                 warm_start=warm_start, verbose=verbose, verbose_interval=verbose_interval)

print("Execution Completed")

Execution Completed


### 5.3 GMM Clustering Model Fitting

In [35]:
# Fitting the GMM Clustering Model

print("GMM Clustering Model Training Started...")

gmm_model.fit(image1_reshape)

print("GMM Clustering Model Training Completed...")

GMM Clustering Model Training Started...
GMM Clustering Model Training Completed...


### 5.3 GMM Clustering Model Predictions

In [36]:
# Evaluating the GMM Clustering Model Predictions

gmm_image1_predictions = gmm_model.predict(image1_reshape)

print("Execution Completed")

Execution Completed


In [37]:
# Displaying the Prediction Results

gmm_image1_predictions

array([2, 2, 0, ..., 3, 0, 0])

In [38]:
# verifying the Shape of the Predictions Array

gmm_image1_predictions.shape

(881664,)

### 5.4 Evaluating the Predictions Results

In [39]:
# Extracting the Original Image Shape before Reshaping
original_image1_shape = image1.shape

original_image1_shape

(861, 1024, 3)

In [40]:
original_image1_shape[0]

861

In [41]:
original_image1_shape[1]

1024

In [42]:
original_image1_shape[2]

3

In [43]:
# Reshaping the Original Image with the Predicted Cluster Labels

segmented_array1 = gmm_predictions.reshape(original_image1_shape[0], original_image1_shape[1])

print("Execution Completed")

Execution Completed


In [44]:
# Displaying the Reshaped Segmented Array with Predictions 

segmented_array1

array([[2, 2, 0, ..., 0, 2, 2],
       [2, 2, 0, ..., 0, 0, 2],
       [0, 2, 2, ..., 0, 0, 2],
       ...,
       [0, 3, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 3, 3, ..., 3, 2, 0]])

In [45]:
# Verifying the Shape of the Reshaped Segmented Array with Predictions 

segmented_array1.shape

(861, 1024)

In [46]:
# Verifying the First Data Instance of the Reshaped Segmented Array with Predictions 

segmented_array1[0]

array([2, 2, 0, ..., 0, 2, 2])

In [47]:
# Verifying the First Data Instance of the Reshaped Segmented Array with Predictions 

segmented_array1[0].shape

(1024,)

### 5.5 Visualizing the Segmented Image with Clusters

In [48]:
# Visualizing the Segmented Image

segmented_image1 = cv2.imwrite("/content/drive/MyDrive/~~~VP_Data_Science/DS_Real_Time_Projects/Image_Segmentation_Using_UnSupervised_Gaussian_Mixture_Model_GMM_Clustering/results/segmented_rock.jpg", segmented_array1)

print("Segmented Image Export Completed")

Segmented Image Export Completed
